// <auto-generated />
namespace HRPaver_Social_Media.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class commentphotoadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentphotoadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201505132255068_commentphotoadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
